#cloud-config
packages:
  - lib32gcc1
  - wget
  - ca-certificates
users:
  - name: abyx
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsbP2NWjLUMLH5dIjwZx44VI2cJ++YmOvNi9U9lKH77Cq0Tex8dfS2SbixDyGonlXP77iHRlvqkYYlRxtIdqnPSjt1wNIQP7TTLM5Nqq2h0VNb7dWGZ5X4/exalDQndIa5T97SgncooLDshS3eGe0Mm/7Tpchrc4QOqtdfJoBMjACUZEPLNuicpKGexUt0E+OncVHmbFp0bjJoHTUbNUQFLhDKWsmBEbaxiyCTqRXIuVeZhFSj5lD5ezAtVp8V8A4sldoAVtwbkBJKcqqCx4XZGx8U6zyHyIgJOcK6AvqfalNpA4GlpAVh94kAxBjv+Js8MIahbIGPF2yirWG335PEQ== me@home
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfGkjydwgjvOG/1eeODMws5oMBWuTK2jajgXxpHC5H2PItz/wQBv058dHGQPkAX4Mg8dkfDpUnUvPc0Vn6YNbp4btSmwDUwdcWsdvMZi1re7jp3mArWznSsxlDsqCKs0vvB/0URbEHL0XXQWppUchWvlHI56iZEOoqAfNpAqlpER4eT4qmLyRLQald0+6W9m73CQBqSem6dY8e3FCtZbdxqf1GETErokeBZRYL29XKKli1pXCC3alJBgaCpvqlpnWN9AiSYEnHePVUVdj8oqPj1KgR005WD//WfOmInDUYds9VrJoGEU1j7DwuBPKUp+WoAEIe6DOf+7+WNnA1ZUDn me@work
  - name: squad
    sudo: False
write_files:
  - path: /home/squad/run-server.sh
    permissions: '0555'
    content: |
      #!/bin/bash
      set -e
      /home/squad/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/squad/server +app_update 403240 +quit
      /home/squad/server/SquadGameServer.sh Port=7787 QueryPort=27165 RCONIP=127.0.0.1 RCONPASSWORD=1
  - path: /etc/systemd/system/squad.service
    content: |
      [Unit]
      Description=Squad Server
      Wants=network-online.target
      After=network-online.target
      StartLimitIntervalSec=0

      [Service]
      Type=simple
      Restart=always
      RestartSec=1
      User=squad
      ExecStart=/bin/bash /home/squad/run-server.sh

      [Install]
      WantedBy=multi-user.target
  - path: /usr/local/bin/rcon
    permissions: '0555'
    content: |
      #!/bin/bash
      PWD=1
      CMD_LEN=$(echo -n "$*" | awk '{printf "%c", length($0)+10}')
      echo -ne "\x0b\0\0\0id-1\x03\0\0\x00$PWD\0\x00$CMD_LEN\0\0\0id-2\x02\0\0\x00$*\0\0" | nc -w1 localhost 21114 | tail -c+41 | head -c-2
  - path: /etc/cron.d/squad
    content: |
      SHELL=/bin/bash
      00 * * * * squad /usr/local/bin/rcon AdminBroadcast Automatic map change in 1 minute
      01 * * * * squad /usr/local/bin/rcon AdminEndMatch
  - path: /home/squad/setup.sh
    permissions: '0555'
    content: |
      #!/bin/bash
      set -e

      # Download steamcmd.
      mkdir /home/squad/steamcmd
      cd /home/squad/steamcmd
      wget 'https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz' -O setup_steamcmd.tgz
      tar xvf setup_steamcmd.tgz

      # Install squad server.
      ./steamcmd.sh +login anonymous +force_install_dir /home/squad/server +app_update 403240 validate +quit

      # Change config.
      cd /home/squad/server/SquadGame/ServerConfig

      sed -i -r 's/^(ServerName)=.*/\1="Finch'"'"'s Sandbox"/' Server.cfg
      sed -i -r 's/^(MaxPlayers)=.*/\1=12/' Server.cfg
      sed -i -r 's/^(NumReservedSlots)=.*/\1=1/' Server.cfg
      sed -i -r 's/^(PreventTeamChangeIfUnbalanced)=.*/\1=false/' Server.cfg
      sed -i -r 's/^(TKAutoKickEnabled)=.*/\1=false/' Server.cfg

      echo "" > ServerMessages.cfg

      cat << '__end_of_file__' >> Admins.cfg
      Group=All:changemap,pause,cheat,private,balance,chat,kick,ban,config,cameraman,immunity,featuretest,reserve,debug,teamchange,forceteamchange,canseeadminchat
      Group=Mod:changemap,cheat,chat,cameraman,featuretest,reserve,teamchange,forceteamchange
      Admin=76561198126672787:All
      Admin=76561198012819918:Mod
      __end_of_file__

      cat << '__end_of_file__' > MapRotation.cfg
      Jensen's Range v1
      Jensen's Range v2
      Jensen's Range v3
      __end_of_file__

      cat << '__end_of_file__' > MOTD.cfg
      Open training server.

      Automatic map change at the beginning of every hour.
      __end_of_file__
runcmd:
  - 'chown -R squad:squad /home/squad'
  - sudo -u squad bash /home/squad/setup.sh
  - systemctl enable squad
  - systemctl start squad
